project:
  type: website

website:
  title: "tcrenv"
  navbar:
    left:
      - href: index.qmd
    right:
      - text: Sessions
        menu:
          - intro.qmd
          - installing.qmd
          - import.qmd
          - tidy.qmd
          - visualization1.qmd
          - transformation1.qmd
          - transformation2.qmd
          - mar.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



