---
warning: FALSE
message: FALSE
format:
  html:
    toc: false
---

## Introduction to R - GROFTP, winter 2025

The course is aimed at fellows with no or very limited experience in R. It will cover the fundamental/generic basis of the grammar of data and graphics and reproducible document writing where R is used as the sole working medium. The framework introduced is based on using a set of packages that use internally consistent R-dialect that falls under the tidyverse umbrella.

This space is **here**: [https://heima.hafro.is/~einarhj/edu/2025groftp](https://heima.hafro.is/~einarhj/edu/2025groftp)


### Objective

The objective of the course is to provide participants with a solid foundation in efficient use of the R environment using various types of marine data sets as case examples. Emphasis will be put on data munging and literate programming starting with importing "raw" data and culminating with deliverance of publishable output produced from a single coded document file.

By the end of the course, the participants:

* Will be able to import data from multitude of sources computer (i.e. own text files, excel, access, sql databases).
* Will be able to clean, manipulate, explore, summarize and graph data.
* Will be able to apply the principle of reproducible analysis and report writing from A through Z which are then deliverable through any of the current three common deliverable formats: .html, .pdf and .docx.

einar.hjorleifsson@gmail.com

## Agenda

This is space in the making meaning that the content is **preliminary**.

#### 2025-01-06 10:00 - 12:00  (Monday)

- [Introduction](intro.qmd)

#### 2025-01-06 13:00 - 16:00  (Monday)

- [Getting started with ggplot](visualization1.qmd)


#### 2025-01-07 09:00 - 12:00  (Tuesday)

- [Data transformation 1](transformation1.qmd)

#### 2025-01-08 09:00 - 12:00  (Wednesday)

- [Data transformation 2](transformation2.qmd)

#### 2025-01-09 09:00 - 12:00  (Thursday)

- [Data import](import.qmd)

#### 2025-01-10 10:00 - 12:00  (Friday)

- [More ggplot - maps](visualization2.qmd)

#### 2025-01-10 13:00 - 16:00  (Friday)

- [Reproducible research with R](reproducable.qmd)


#### 2025-01-13 10:00 - 16:00  (Monday)

teacher was sick


#### 2025-01-15 10:00 - 16:00  (Wednesday)

* [Data transformation 2 - second half](transformation2.qmd)
* [Tidy dataframes](tidy.qmd)

#### 2025-01-16 09:00 - 12:00  (Thursday)

* [Functions](functions.qmd)

#### 2025-02-XX

*Ad hoc* meetings once you are in your project. We could think of this in two ways:

* Common session where all attend - you have to think about topics to cover and I will try to accomodate them
* One on one session - individual session where I try to help a fellow with importing and tidying your data structure. Remember that it is your superviser that should really help you with this.

Now, keep in mind that my time for this is not limitless.

## Bit

[bit](bit.qmd)